version: "3"
services:
  chrome:
    image: selenium/node-chrome:3.14.0-gallium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub


  firefox:
    image: selenium/node-firefox:3.14.0-gallium
    volumes:
       - /dev/shm:/dev/shm
    depends_on:
       - hub
    environment:
        HUB_HOST: hub

  hub:
    image: selenium/hub:3.14.0-gallium
    ports:
      - "4444:4444"


  automation_sample:
    image: "guillermoendava/automationrepository:automationdockerendava"
    build: .
    command: bash -c "mvn test -Dhub='http://selenium-hub:4444/wd/hub' -Dbrowser=chrome"
    depends_on:
      - chrome
