version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.0.0-rc-2-prerelease-20210908
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"
  hub:
    image: selenium/hub:4.0.0-rc-2-prerelease-20210908
    container_name: hub
    ports:
     - "4442:4442"
     - "4443:4443"
     - "4444:4444"

  automation_sample:
   image: "guillermoendava/automationrepository:automationdockerendava"
   build: .
   command: bash -c "mvn test -Pgrid -Pheadless -Pchrome -Dgrid.url='http://localhost:4444/wd/hub'"
   depends_on:
     - chrome
